---
title: "Feature Development"
author: "Zach Austin"
date: '2022-12-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

rm(list=ls())

```

```{r}

project_name = "ML-MADNESS"

require(stringr)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
repo_path = file.path(substr(getwd(),0,gregexpr(pattern = project_name ,
                                                getwd())[[1]][1]-2),
                      project_name)

source(file.path(repo_path,
                 'objects',
                 'load_directories.r'),
       local = knitr::knit_global())

p <- c("tidyverse","zoo",
       "lubridate",
       "ggplot2","ggdark",
       "caTools","rminer","ROCR",
       "hydroGOF","e1071","xgboost",
       "OptimalCutpoints","caret",
       "parallel")

load_all_packages(p)

```

```{r}

boxscores = read.csv(file.path(data_path,"raw","box","bs_ALL.csv"))

```

```{r}


team_off_data = boxscores %>% 
  select(team_id,team_display_name,
         game_id,game_date,
         field_goals_made_field_goals_attempted,three_point_field_goals_made_three_point_field_goals_attempted,
         free_throws_made_free_throws_attempted,offensive_rebounds,defensive_rebounds,
         assists,steals,blocks,turnovers,team_turnovers,total_turnovers,technical_fouls,
         flagrant_fouls,fouls,largest_lead,
         home_away,
         opponent_id) %>% 
  arrange(desc(game_date)) %>% # Fix home_away
  mutate(home_away = ifelse(home_away=="HOME","AWAY","HOME")) %>% 
  separate(col=field_goals_made_field_goals_attempted,
           into = c("FGM","FGA"),sep="-") %>% 
  separate(col=three_point_field_goals_made_three_point_field_goals_attempted,
           into = c("FG3M","FG3A"),sep="-") %>% 
  separate(col=free_throws_made_free_throws_attempted,
           into = c("FTM","FTA"),sep="-") %>% 
  mutate(FGM = as.numeric(FGM),
         FGA = as.numeric(FGA),
         FTM = as.numeric(FTM),
         FTA = as.numeric(FTA),
         FG3M = as.numeric(FG3M),
         FG3A = as.numeric(FG3A)) %>% 
  mutate(PTS = 2 * FGM + 1 * FG3M + 1 * FTM)

# Note *.x refers to team, *.y refers to (team allowed)
all_team_data = team_off_data %>% 
  left_join(team_off_data,by=c("opponent_id"="team_id","game_id","game_date")) %>% 
  mutate(winning_margin = PTS.x - PTS.y,
         game_total = PTS.x + PTS.y) %>% 
  mutate(game_date = as.Date(game_date)) %>% 
  mutate(SEASON = ifelse(month(as.POSIXlt(game_date, format="Y-m-d"))>5,
                         year(as.POSIXlt(game_date, format="Y-m-d"))+1,
                         year(as.POSIXlt(game_date, format="Y-m-d")))) %>% 
  # Identify appearance number
  group_by(SEASON,team_id) %>% 
  arrange(SEASON,team_id,game_date) %>% 
  mutate(APPEARANCE = row_number()) %>% 
  ungroup()

all_team_data = all_team_data %>% 
  left_join(all_team_data %>% 
              select(game_id,team_id,APPEARANCE) %>% 
              rename("OPP_APPEARANCE"="APPEARANCE"),by=c("opponent_id"="team_id","game_id"))
  


```

```{r}

# Some cleanup

# Extract team ID and name

team_info = all_team_data %>%
  ungroup() %>% 
  select(team_id,team_display_name.x) %>% 
  group_by(team_id,team_display_name.x) %>% 
  summarize(APPEARANCES = n()) %>% 
  rename("team_name" = "team_display_name.x") %>% 
  arrange(desc(APPEARANCES))

```

# Feature Design

Inputs:
- Team Name
- Game Date
- Observation Window (Season)
- Opponent Name

Returns:
- Feature indicated (for team achieved / allowed)
- Options:
  - Rolling average
  - ELO Based

```{r}

team_data_refined = all_team_data %>% 
  ungroup() %>% 
  select(-c(team_display_name.x,team_display_name.y))


```

# Calculate ELO for a specific feature

- Example: feature: PTS scored, defending feature: PTS allowed

```{r}

calculate_relative_elo <- function(team_data_refined,
                                   feature,
                                   season,
                                   rename_f = ""){
  
  columns = c("game_date","game_id","team_id","opponent_id","APPEARANCE","OPP_APPEARANCE",
              feature)
  
  temp = team_data_refined %>% 
    filter(SEASON==season) %>% 
    select(columns) %>% 
    arrange(APPEARANCE) %>% 
    group_by(APPEARANCE) %>% 
    mutate(F_AVG = mean(!!as.name(feature)),
           F_SD = sd(!!as.name(feature))) %>% 
    ungroup() %>% 
    mutate(
      PERF = (!!as.name(feature) - F_AVG)/F_SD,
    )
  
  if(rename_f!=""){
    feature = rename_f
  }
  
  temp = temp %>% 
    mutate("{feature}_ELO" := 2000,
           "{feature}_DEF_ELO" := 2000, # Corresponds to opponent
           "{feature}_ELO_NEXT" := 2000,
           "{feature}_DEF_ELO_NEXT" := 2000) %>% 
    arrange(game_date)
  
  for(r in 1:nrow(temp)){
    
    row = temp[r,]
    team = row$team_id
    opp = row$opponent_id
    
    if(row$APPEARANCE!=1){
      # Set row {feature}_ELO to {feature}_ELO_NEXT from prior appearance
      t_pa = temp %>% 
        filter(APPEARANCE == row$APPEARANCE - 1,
               team_id == team)
      row[[paste0(feature,"_ELO")]] = t_pa[[paste0(feature,"_ELO_NEXT")]]
    }
    if(row$OPP_APPEARANCE!=1){
      # Set row {defending_feature}_ELO to {defending_feature}_ELO_NEXT from prior appearance by opponent
      o_pa = temp %>% 
        filter(APPEARANCE == row$OPP_APPEARANCE - 1,
               team_id == opp)
      row[[paste0(feature,"_DEF_ELO")]] = o_pa[[paste0(feature,"_DEF_ELO_NEXT")]]
    }
    
    perf = ifelse(is.nan(row$PERF),0,row$PERF)

    # Negative should hurt feature, benefit d_feature
    # Weight of benefit should be impacted by pregame opinion on strengths
    
    w_prob = row[[paste0(feature,"_ELO")]] / (row[[paste0(feature,"_ELO")]] + 
                                                row[[paste0(feature,"_DEF_ELO")]])
    
    # W_prob > 0.5 means team should have advantage... smaller change if positive perf
    f_elo_change = ifelse(w_prob >= 0.5, 2*(w_prob-0.5)**2+0.5 , 1 - 2*(w_prob-0.5)**2+0.5) * 100 * perf 
    

    row[[paste0(feature,"_ELO_NEXT")]] =  row[[paste0(feature,"_ELO")]] + f_elo_change
    row[[paste0(feature,"_DEF_ELO_NEXT")]] = row[[paste0(feature,"_DEF_ELO")]] - f_elo_change
    
    temp[r,] = row
    
    if(r%%200==0){
      print(r)
    }
    
  }
  return(temp)
  
}

df = calculate_relative_elo(team_data_refined = team_data_refined,
                            features = "PTS.x",
                            season = 2022,
                            rename_fs = "PTS_SCORED")


```
```{r}

set.seed(2)


modeling=df

predictors = c('PTS_SCORED_ELO','PTS_SCORED_DEF_ELO')



sample = sample.split(modeling$PTS.x,SplitRatio = .8)
train_data = subset(modeling, sample == TRUE)
test_data  = subset(modeling, sample == FALSE)

train_d_predictors <- train_data %>%
  select(predictors)
tst_d_predictors<- test_data %>%
  select(predictors)

dtrain <- xgb.DMatrix(data = as.matrix(train_d_predictors),
                      label = as.numeric(train_data$PTS.x))
# Create test matrix
dtest <- xgb.DMatrix(data = as.matrix(tst_d_predictors),
                     label = as.numeric(test_data$PTS.x))


bst <- xgboost(data = dtrain, # Set training data

               eta =  .01, # Set learning rate
               nrounds = 300, # Set number of rounds
               early_stopping_rounds = 40, # Set number of rounds to stop at if there is no improvement

               verbose = 1, # 1 - Prints out fit
               nthread = 3, # Set number of parallel threads
               print_every_n = 20, # Prints out result every 20th iteration

               objective = "reg:squarederror", # Set objective
               eval_metric = "rmse")

boost_preds <- predict(bst, dtest) # Create predictions for XGBoost model

res = data.frame(boost_preds,test_data)

t = res %>% 
  filter(APPEARANCE!=1)
mean(abs(t$PTS.x - t$boost_preds))

imp_mat <- xgb.importance(model = bst)
# Plot importance (top 10 variables)
xgb.plot.importance(imp_mat, top_n = 10)


```


